=== NHSDigital/multicast-notification-service/signal-schemas/fhirsignal.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "MNS Signal in FHIR R4 Format representation schema",
  "type": "object",
  "description": "A wrapper object for the MNS Signal, and optionally the hydrated signal",
  "properties": {
    "resourceType": {
      "const": "Bundle"
    },
    "id": {
      "type": "string",
      "description": "Event ID",
      "examples": [
        "236a1d4a-5d69-4fa9-9c7f-e72bf505aa5b"
      ]
    },
    "type": {
      "const": "history"
    },
    "timestamp": {
      "type": "string",
      "description": "ISO-8601 timestamp signifying the time of the occurrence",
      "format": "date-time",
      "examples": [
        "2020-06-01T13:00:00Z"
      ]
    },
    "entry": {
      "type": "array",
      "prefixItems": [
        {
          "$ref": "#/$defs/mns-fhir-signal"
        },
        {
          "$ref": "#/$defs/hydrated-signal"
        }
      ],
      "items": false,
      "minItems": 1,
      "maxItems": 2
    }
  },
  "required": [
    "resourceType",
    "id",
    "type",
    "timestamp",
    "entry"
  ],
  "$defs": {
    "mns-fhir-signal": {
      "type": "object",
      "description": "The MNS Signal",
      "properties": {
        "fullUrl": {
          "type": "string",
          "description": "A temporary ID for the resource",
          "pattern": "^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
          "examples": [
            "urn:uuid:9155bdda-35c9-44d0-a772-37abd7870e5c"
          ]
        },
        "resource": {
          "type": "object",
          "properties": {
            "resourceType": {
              "const": "Parameters"
            },
            "meta": {
              "type": "object",
              "properties": {
                "profile": {
                  "type": "array",
                  "minItems": 1,
                  "maxItems": 1,
                  "items": {
                    "const": "http://hl7.org/fhir/uv/subscriptions-backport/StructureDefinition/backport-subscription-status-r4"
                  }
                }
              },
              "required": [
                "profile"
              ]
            },
            "id": {
              "type": "string",
              "description": "Temporary ID for resource. Matches fullUrl minus `urn:uuid:`.",
              "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
              "examples": [
                "9155bdda-35c9-44d0-a772-37abd7870e5c"
              ]
            },
            "parameter": {
              "type": "array",
              "items": false,
              "minItems": 5,
              "maxItems": 5,
              "prefixItems": [
                {
                  "type": "object",
                  "properties": {
                    "name": {
                      "const": "subscription"
                    },
                    "valueReference": {
                      "type": "object",
                      "properties": {
                        "reference": {
                          "type": "string",
                          "description": "The MNS subscriptions endpoint",
                          "format": "uri",
                          "examples": [
                            "https://api.service.nhs.uk/multicast-notification-service/subscriptions"
                          ]
                        }
                      },
                      "required": [
                        "reference"
                      ]
                    }
                  },
                  "required": [
                    "name",
                    "valueReference"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "name": {
                      "const": "status"
                    },
                    "valueCode": {
                      "const": "active"
                    }
                  },
                  "required": [
                    "name",
                    "valueCode"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "name": {
                      "const": "type"
                    },
                    "valueCode": {
                      "const": "event-notification"
                    }
                  },
                  "required": [
                    "name",
                    "valueCode"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "name": {
                      "const": "notification-event"
                    },
                    "part": {
                      "type": "array",
                      "minItems": 3,
                      "maxItems": 3,
                      "items": false,
                      "prefixItems": [
                        {
                          "type": "object",
                          "description": "Note this is a fixed value",
                          "properties": {
                            "name": {
                              "const": "event-number"
                            },
                            "valueString": {
                              "const": "1"
                            }
                          },
                          "required": [
                            "name",
                            "valueString"
                          ]
                        },
                        {
                          "type": "object",
                          "description": "The times of the occurrence",
                          "properties": {
                            "name": {
                              "const": "timestamp"
                            },
                            "valueInstant": {
                              "type": "string",
                              "format": "date-time",
                              "examples": [
                                "2020-06-01T13:00:00Z"
                              ]
                            }
                          },
                          "required": [
                            "name",
                            "valueInstant"
                          ]
                        },
                        {
                          "type": "object",
                          "description": "Resource on an API of the publishing service to retrieve full details of the event (or subject record)",
                          "properties": {
                            "name": {
                              "const": "focus"
                            },
                            "valueReference": {
                              "type": "object",
                              "properties": {
                                "reference": {
                                  "type": "string",
                                  "format": "uri",
                                  "examples": [
                                    "https://api.service.nhs.uk/register-with-a-gp-surgery/applications/bd468854-4cd5-4e57-9dde-e5a482d50605"
                                  ]
                                }
                              },
                              "required": [
                                "reference"
                              ]
                            }
                          },
                          "required": [
                            "name",
                            "valueReference"
                          ]
                        }
                      ]
                    }
                  },
                  "required": [
                    "name",
                    "part"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "name": {
                      "const": "additional-context"
                    },
                    "part": {
                      "type": "array",
                      "minItems": 2,
                      "maxItems": 4,
                      "prefixItems": [
                        {
                          "type": "object",
                          "description": "Describes the occurrence; the name of the event.",
                          "properties": {
                            "name": {
                              "const": "event-type"
                            },
                            "valueString": {
                              "type": "string",
                              "examples": [
                                "gpreg-change-gp-req-1"
                              ]
                            }
                          },
                          "required": [
                            "name",
                            "valueString"
                          ]
                        },
                        {
                          "type": "object",
                          "description": "Identifies the producer of the event. This is usually a service, as listed in the [Service Catalogue](https://digital.nhs.uk/services/service-catalogue).",
                          "properties": {
                            "name": {
                              "const": "source"
                            },
                            "valueUri": {
                              "type": "string",
                              "examples": [
                                "uk.nhs.register-with-a-gp-surgery-service"
                              ]
                            }
                          },
                          "required": [
                            "name",
                            "valueUri"
                          ]
                        }
                      ],
                      "items": {
                        "anyOf": [
                          {
                            "type": "object",
                            "description": "Identifies the subject of the event in the context of the event producer/event type.",
                            "properties": {
                              "name": {
                                "const": "subject"
                              },
                              "valueReference": {
                                "type": "object",
                                "properties": {
                                  "identifier": {
                                    "type": "object",
                                    "properties": {
                                      "value": {
                                        "type": "string",
                                        "examples": [
                                          "9912003888"
                                        ]
                                      }
                                    },
                                    "required": [
                                      "value"
                                    ]
                                  }
                                },
                                "required": [
                                  "identifier"
                                ]
                              }
                            },
                            "required": [
                              "name",
                              "valueReference"
                            ]
                          },
                          {
                            "type": "object",
                            "description": "Version ID related to the event",
                            "properties": {
                              "name": {
                                "const": "version-id"
                              },
                              "valueString": {
                                "type": "string",
                                "examples": [
                                  "1"
                                ]
                              }
                            },
                            "required": [
                              "name",
                              "valueString"
                            ]
                          }
                        ]
                      }
                    }
                  },
                  "required": [
                    "name",
                    "part"
                  ]
                }
              ]
            },
            "request": {
              "type": "object",
              "properties": {
                "method": {
                  "const": "GET"
                },
                "url": {
                  "type": "string",
                  "format": "uri",
                  "examples": [
                    "https://api.service.nhs.uk/multicast-notification-service/subscriptions"
                  ]
                }
              },
              "required": [
                "method",
                "url"
              ]
            },
            "response": {
              "type": "object",
              "properties": {
                "status": {
                  "const": "200"
                }
              },
              "required": [
                "status"
              ]
            }
          },
          "required": [
            "resourceType",
            "meta",
            "id",
            "parameter"
          ]
        }
      },
      "required": [
        "fullUrl",
        "resource"
      ]
    },
    "hydrated-signal": {
      "type": "object",
      "description": "For selected event types there is the option to include the hydrated signal alongside the MNS event notification for subscribers who are unable to retrieve the record from the publisher API due to technical constraints.\nThe hydrated signal is a snapshot of the resource at the time of the event, and is as a sibling to the MNS Signal within this wrapper object.\n",
      "properties": {
        "fullUrl": {
          "type": "string",
          "format": "uri",
          "examples": [
            "https://api.service.nhs.uk/register-with-a-gp-surgery/applications/bd468854-4cd5-4e57-9dde-e5a482d50605"
          ]
        },
        "resource": {
          "type": "object",
          "description": "The response from the event publisher's source API, when getting the resource as specified in the event and reflected in the `fullUrl` sibling key."
        },
        "request": {
          "type": "object",
          "properties": {
            "method": {
              "const": "GET"
            },
            "url": {
              "type": "string",
              "format": "uri",
              "examples": [
                "https://api.service.nhs.uk/register-with-a-gp-surgery/applications/bd468854-4cd5-4e57-9dde-e5a482d50605"
              ]
            }
          },
          "required": [
            "method",
            "url"
          ]
        },
        "response": {
          "type": "object",
          "properties": {
            "status": {
              "const": "200"
            }
          },
          "required": [
            "status"
          ]
        }
      },
      "required": [
        "fullUrl",
        "resource",
        "request",
        "response"
      ]
    }
  }
}

=== NHSDigital/multicast-notification-service/signal-schemas/examples/pdm-resource-change-1/signal.json
{
    "resourceType": "Bundle",
    "id": "02db8069-c190-4e5f-8cd2-0a656563e439",
    "type": "history",
    "timestamp": "2020-06-01T13:00:00Z",
    "entry": [
      {
        "fullUrl": "urn:uuid:02db8069-c190-4e5f-8cd2-0a656563e439",
        "resource": {
          "resourceType": "Parameters",
          "meta": {
            "profile": [
              "http://hl7.org/fhir/uv/subscriptions-backport/StructureDefinition/backport-subscription-status-r4"
            ]
          },
          "id": "02db8069-c190-4e5f-8cd2-0a656563e439",
          "parameter": [
            {
              "name": "subscription",
              "valueReference": {
                "reference": "https://api.service.nhs.uk/multicast-notification-service/subscriptions"
              }
            },
            {
              "name": "status",
              "valueCode": "active"
            },
            {
              "name": "type",
              "valueCode": "event-notification"
            },
            {
              "name": "notification-event",
              "part": [
                {
                  "name": "event-number",
                  "valueString": "1"
                },
                {
                  "name": "timestamp",
                  "valueInstant": "2020-06-01T13:00:00Z"
                },
                {
                  "name": "focus",
                  "valueReference": {
                    "reference": "https://api.service.nhs.uk/patient-data-manager/FHIR/R4/9912003888/f5524783-e5d7-473e-b2a0-29582ff231da"
                  }
                }
              ]
            },
            {
              "name": "additional-context",
              "part": [
                {
                  "name": "event-type",
                  "valueString": "pdm-resource-change-1"
                },
                {
                  "name": "source",
                  "valueUri": "api.service.nhs.uk/patient-data-manager/FHIR/R4/"
                },
                {
                  "name": "subject",
                  "valueReference": {
                    "identifier": {
                      "value": "9912003888"
                    }
                  }
                }
              ]
            }
          ]
        },
        "request": {
          "method": "GET",
          "url": "https://api.service.nhs.uk/multicast-notification-service/subscriptions"
        },
        "response": {
          "status": "200"
        }
      }
    ]
  }

=== NHSDigital/multicast-notification-service/signal-schemas/examples/pds-change-of-gp-2/signal.json
{
    "resourceType": "Bundle",
    "id": "56e9d7db-d70a-48bf-95f8-e779a741382a",
    "type": "history",
    "timestamp": "2020-06-01T13:00:00Z",
    "entry": [
      {
        "fullUrl": "urn:uuid:56e9d7db-d70a-48bf-95f8-e779a741382a",
        "resource": {
          "resourceType": "Parameters",
          "meta": {
            "profile": [
              "http://hl7.org/fhir/uv/subscriptions-backport/StructureDefinition/backport-subscription-status-r4"
            ]
          },
          "id": "56e9d7db-d70a-48bf-95f8-e779a741382a",
          "parameter": [
            {
              "name": "subscription",
              "valueReference": {
                "reference": "https://api.service.nhs.uk/multicast-notification-service/subscriptions"
              }
            },
            {
              "name": "status",
              "valueCode": "active"
            },
            {
              "name": "type",
              "valueCode": "event-notification"
            },
            {
              "name": "notification-event",
              "part": [
                {
                  "name": "event-number",
                  "valueString": "1"
                },
                {
                  "name": "timestamp",
                  "valueInstant": "2020-06-01T13:00:00Z"
                },
                {
                  "name": "focus",
                  "valueReference": {
                    "reference": "https://api.service.nhs.uk/personal-demographics/FHIR/R4/Patient/9912003888"
                  }
                }
              ]
            },
            {
              "name": "additional-context",
              "part": [
                {
                  "name": "event-type",
                  "valueString": "pds-change-of-gp-2"
                },
                {
                  "name": "source",
                  "valueUri": "https://fhir.nhs.uk/Id/nhsSpineASID/477121000324"
                },
                {
                  "name": "subject",
                  "valueReference": {
                    "identifier": {
                      "value": "9912003888"
                    }
                  }
                }
              ]
            }
          ]
        },
        "request": {
          "method": "GET",
          "url": "https://api.service.nhs.uk/multicast-notification-service/subscriptions"
        },
        "response": {
          "status": "200"
        }
      }
    ]
  }

=== NHSDigital/multicast-notification-service/signal-schemas/examples/pathology-laboratory-reporting-test-result-stored-1/signal.json
{
    "resourceType": "Bundle",
    "id": "236a1d4a-5d69-4fa9-9c7f-e72bf505aa5b",
    "type": "history",
    "timestamp": "2020-06-01T13:00:00Z",
    "entry": [
      {
        "fullUrl": "urn:uuid:236a1d4a-5d69-4fa9-9c7f-e72bf505aa5b",
        "resource": {
          "resourceType": "Parameters",
          "meta": {
            "profile": [
              "http://hl7.org/fhir/uv/subscriptions-backport/StructureDefinition/backport-subscription-status-r4"
            ]
          },
          "id": "236a1d4a-5d69-4fa9-9c7f-e72bf505aa5b",
          "parameter": [
            {
              "name": "subscription",
              "valueReference": {
                "reference": "https://api.service.nhs.uk/multicast-notification-service/subscriptions"
              }
            },
            {
              "name": "status",
              "valueCode": "active"
            },
            {
              "name": "type",
              "valueCode": "event-notification"
            },
            {
              "name": "notification-event",
              "part": [
                {
                  "name": "event-number",
                  "valueString": "1"
                },
                {
                  "name": "timestamp",
                  "valueInstant": "2020-06-01T13:00:00Z"
                },
                {
                  "name": "focus",
                  "valueReference": {
                    "reference": "https://api.service.nhs.uk/patient-data-manager/FHIR/R4/Bundle/b0b97bff-e3d7-4744-a09a-e55781886dd0"
                  }
                }
              ]
            },
            {
              "name": "additional-context",
              "part": [
                {
                  "name": "event-type",
                  "valueString": "pathology-laboratory-reporting-test-result-stored-1"
                },
                {
                  "name": "source",
                  "valueUri": "uk.nhs.pathology-laboratory-reporting"
                },
                {
                  "name": "subject",
                  "valueReference": {
                    "identifier": {
                      "value": "9912003888"
                    }
                  }
                }
              ]
            }
          ]
        },
        "request": {
          "method": "GET",
          "url": "https://api.service.nhs.uk/multicast-notification-service/subscriptions"
        },
        "response": {
          "status": "200"
        }
      }
    ]
  }

=== NHSDigital/multicast-notification-service/signal-schemas/examples/vrs-proxy-role-created-1/signal.json
{
  "resourceType": "Bundle",
  "id": "898cc706-9156-4d67-941a-b37ca9a85861",
  "type": "history",
  "timestamp": "2026-02-27T11:47:12.157887+00:00",
  "entry": [
    {
      "fullUrl": "urn:uuid:212513f9-694d-4735-a9c7-8dca94fea66b",
      "resource": {
        "resourceType": "Parameters",
        "meta": {
          "profile": [
            "http://hl7.org/fhir/uv/subscriptions-backport/StructureDefinition/backport-subscription-status-r4"
          ]
        },
        "id": "212513f9-694d-4735-a9c7-8dca94fea66b",
        "parameter": [
          {
            "name": "subscription",
            "valueReference": {
              "reference": "https://api.service.nhs.uk/multicast-notification-service/subscriptions"
            }
          },
          {
            "name": "status",
            "valueCode": "active"
          },
          {
            "name": "type",
            "valueCode": "event-notification"
          },
          {
            "name": "notification-event",
            "part": [
              {
                "name": "event-number",
                "valueString": "1"
              },
              {
                "name": "timestamp",
                "valueInstant": "2026-02-27T11:47:12.157887+00:00"
              },
              {
                "name": "focus",
                "valueReference": {
                  "reference": "https://api.service.nhs.uk/validated-relationships/FHIR/R4/Consent/ecc32c41"
                }
              }
            ]
          },
          {
            "name": "additional-context",
            "part": [
              {
                "name": "event-type",
                "valueString": "vrs-proxy-role-created-1"
              },
              {
                "name": "source",
                "valueUri": "uk.nhs.validated-relationships-service"
              },
              {
                "name": "subject",
                "valueReference": {
                  "identifier": {
                    "value": "9912003888"
                  }
                }
              }
            ]
          }
        ]
      },
      "request": {
        "method": "GET",
        "url": "https://api.service.nhs.uk/multicast-notification-service/subscriptions"
      },
      "response": {
        "status": "200"
      }
    }
  ]
}

=== NHSDigital/multicast-notification-service/signal-schemas/examples/imms-vaccinations-1/signal.json
{
  "resourceType": "Bundle",
  "id": "e0b3d12f-c64d-4b29-b23b-4a670941f572",
  "type": "history",
  "timestamp": "2026-03-04T16:45:49.054765+00:00",
  "entry": [
    {
      "fullUrl": "urn:uuid:ea8ab860-1005-4f6a-a090-3e596f5af323",
      "resource": {
        "resourceType": "Parameters",
        "meta": {
          "profile": [
            "http://hl7.org/fhir/uv/subscriptions-backport/StructureDefinition/backport-subscription-status-r4"
          ]
        },
        "id": "ea8ab860-1005-4f6a-a090-3e596f5af323",
        "parameter": [
          {
            "name": "subscription",
            "valueReference": {
              "reference": "https://api.service.nhs.uk/multicast-notification-service/subscriptions"
            }
          },
          {
            "name": "status",
            "valueCode": "active"
          },
          {
            "name": "type",
            "valueCode": "event-notification"
          },
          {
            "name": "notification-event",
            "part": [
              {
                "name": "event-number",
                "valueString": "1"
              },
              {
                "name": "timestamp",
                "valueInstant": "2026-03-04T16:45:49.054765+00:00"
              },
              {
                "name": "focus",
                "valueReference": {
                  "reference": "https://int.api.service.nhs.uk/immunisation-fhir-api/Immunization/29dc4e84-7e72-11ee-b962-0242ac120002"
                }
              }
            ]
          },
          {
            "name": "additional-context",
            "part": [
              {
                "name": "event-type",
                "valueString": "imms-vaccination-1"
              },
              {
                "name": "source",
                "valueUri": "int.api.service.nhs.uk/immunisation-fhir-api"
              },
              {
                "name": "subject",
                "valueReference": {
                  "identifier": {
                    "value": "9912003888"
                  }
                }
              }
            ]
          }
        ]
      },
      "request": {
        "method": "GET",
        "url": "https://api.service.nhs.uk/multicast-notification-service/subscriptions"
      },
      "response": {
        "status": "200"
      }
    }
  ]
}
